# Generated by Django 2.0 on 2017-12-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPortalApp', '0002_auto_20171221_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_of_publication',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Короткое описание (до 2000 знаков)'),
        ),
        migrations.AlterField(
            model_name='place_of_publication',
            name='list_of_links',
            field=models.TextField(verbose_name='Список ссылок'),
        ),
        migrations.AlterField(
            model_name='place_of_publication',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place_of_publication',
            name='place_of_publish',
            field=models.CharField(max_length=255, verbose_name='Место издания'),
        ),
        migrations.AlterField(
            model_name='place_of_publication',
            name='publishing_house',
            field=models.CharField(max_length=255, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='place_of_publication',
            name='type_of_place',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
    ]
