# Generated by Django 2.0 on 2017-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPortalApp', '0003_auto_20171221_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type_of_publication',
            field=models.CharField(max_length=255, verbose_name='Тип публикации '),
        ),
    ]
