# Generated by Django 2.0 on 2017-12-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPortalApp', '0004_auto_20171221_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_of_publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_pub', to='UPortalApp.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='UPortalApp.Publication')),
            ],
        ),
    ]
